####################################################################################
# 系统运行相关配置
####################################################################################
system:
  # 监听地址
  listen: 0.0.0.0
  # 监听端口
  port: 12580
  # API 接口前缀
  api-prefix: /api
  # API 接口版本
  api-version: v1

####################################################################################
# 日志配置
####################################################################################
log:
  # 是否打印日志到文件，容器环境不推荐保存日志到文件
  enabled: false
  # 日志等级，参考 zapcore.Level（-1<=level<=5，-1 / DEBUG）
  level: -1
  # 日志保存目录
  path: logs
  # 日志切割配置，单位 M
  max-size: 100
  # 日志保留天数
  max-age: 7
  # 日志保留个数
  max-backups: 10
  # 是否压缩
  compress: false

####################################################################################
# 数据库配置
####################################################################################
mysql:
  # 主机地址
  host: 127.0.0.1
  # 端口
  port: 3306
  # 数据库
  database: pandora
  # 用户名
  username: root
  # 密码
  password: 123456
  # 字符集
  charset: utf8mb4
  # 排序规则
  collation: utf8mb4_bin
  # 超时时间，单位毫秒
  timeout: 1000
  # 额外参数
  extra-param: parseTime=True&loc=Local
  # 最大打开链接数
  max-open-conns: 100
  # 最大空闲连接数
  max-idle-conns: 10
  # 空闲连接最大超时时间，单位分钟
  max-idle-time: 30